# Generated by Django 5.0.4 on 2024-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_stu_data_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='address',
            field=models.CharField(default='', max_length=70),
        ),
    ]
