# Generated by Django 5.0.4 on 2024-11-08 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0003_alter_stu_data_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
