# Generated by Django 5.0.4 on 2024-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0006_alter_stu_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
